FROM python:3.10.12-slim

WORKDIR /app/

COPY requirements.txt requirements.txt

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["flask" "--app" "server.py" "run"]

# CMD ["gunicorn", "--bind", "0.0.0.0:5000", "server:app"]